name: ExtraUtils
main: me.chickfla.extrautils.ExtraUtils
version: 1.0.0
discription: A plugin that offers utilities for plugins written for a specific server.  It also provides extra commands so you can see what the classes and class-methods do.  
commands:
   distance:
      description: Get distance of 2 players.
      usage: /distance <player1> <player2>
